name: Terraform Init/Plan/Apply workflow

on:
  push:
    branches:
      - '**'

jobs:
  terraform:
    name: Terraform Init/Plan/Apply through workflow
    runs-on: ubuntu-latest

    env:
      AWS_ACCESS_KEY_ID: AKIAUFSEEQX4O227PWGG
      AWS_SECRET_ACCESS_KEY: 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
      AWS_REGION: eu-north-1

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ env.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ env.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Set up Terraform v1.7.5
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.7.5

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        run: terraform plan

      - name: Terraform Apply (Auto-Approve)
        run: terraform apply -auto-approve

